package com.docu.editor.domain.model

import android.graphics.Bitmap
import com.docu.editor.core.ocr.model.DetectedTextItem

enum class EditorToolMode {
    CANVA_STUDIO, // Clean, pro document workspace (Zero unwanted boxes)
    TEXT_EDIT,
    LASSO_SELECT,
    ADD_TEXT,
    WHITEOUT,
    HIGHLIGHTER,
    MARKUP_PEN,
    FILTERS,
    CROP_DESKEW,
    BOOK_DEWARP,
    WATERMARK,
    SIGNATURE,
    PDF_TOOLS,
    REDACTION,
    SHAPES,
    MAGIC_ERASER,
    INSERT_IMAGE,
    CANVA_STICKERS
}

enum class ShapeType(val displayName: String, val icon: String = "⬛") {
    RECTANGLE("Rectangle", "⬛"),
    ROUNDED_RECTANGLE("Rounded Rect", "▢"),
    CIRCLE("Circle", "⚪"),
    OVAL("Oval", "⬭"),
    LINE("Line", "━"),
    ARROW("Arrow", "➔"),
    DOUBLE_ARROW("Double Arrow", "↔"),
    TRIANGLE("Triangle", "▲"),
    STAR("Star", "★"),
    HEART("Heart", "♥"),
    CALLOUT_BUBBLE("Speech Bubble", "💬"),
    HEXAGON("Hexagon", "⬡"),
    SHIELD("Shield", "🛡️"),
    CHECKMARK_BADGE("Checkmark", "✅")
}

enum class DocumentFilterMode(val displayName: String) {
    ORIGINAL("Original"),
    MAGIC_COLOR("Magic Color"),
    SHADOW_REMOVER("Remove Shadow"),
    WATERMARK_REMOVER("Erase Watermark"),
    FINGER_REMOVER("Remove Fingers"),
    BOOK_DEWARP("Flatten Book Page"),
    CLEAN_BW("Clean B&W"),
    GRAYSCALE("Grayscale")
}

data class DocumentEditorUiState(
    val originalBitmap: Bitmap? = null,
    val currentBitmap: Bitmap? = null,
    val detectedItems: List<DetectedTextItem> = emptyList(),
    val selectedItem: DetectedTextItem? = null,
    val selectedItems: List<DetectedTextItem> = emptyList(),
    val isNewTextInsertion: Boolean = false,
    val isScanning: Boolean = false,
    val isApplyingEdit: Boolean = false,
    val processingMessage: String? = null,
    val errorMessage: String? = null,
    val successMessage: String? = null,
    val canUndo: Boolean = false,
    val canRedo: Boolean = false,
    val activeToolMode: EditorToolMode = EditorToolMode.CANVA_STUDIO,
    val activeFilter: DocumentFilterMode = DocumentFilterMode.ORIGINAL,
    val showFiltersSheet: Boolean = false,
    val showIdCardDialog: Boolean = false,
    val showSignatureDialog: Boolean = false,
    val showPdfToolboxDialog: Boolean = false,
    val showTargetSizeAdjusterDialog: Boolean = false,
    val showPkiDigitalSignDialog: Boolean = false,
    val pendingSignedPdfFile: java.io.File? = null,
    val showExportDialog: Boolean = false,
    val showWatermarkDialog: Boolean = false,
    val showBookDewarpDialog: Boolean = false,
    val showOcrTextExtractDialog: Boolean = false,
    val showInteractiveCropDialog: Boolean = false,
    val showCloudAiSettingsDialog: Boolean = false,
    val showAcroFormDialog: Boolean = false,
    val hasInteractiveAcroForm: Boolean = false,
    val acroFormFields: List<com.docu.editor.core.pdf.AcroFormFieldItem> = emptyList(),
    val cloudAiStatus: String = "Online",
    val idCardFrontBitmap: Bitmap? = null,
    val idCardBackBitmap: Bitmap? = null,
    val extractedSignature: Bitmap? = null,
    val activeOverlayBitmap: Bitmap? = null,
    val overlayPositionX: Float = 100f,
    val overlayPositionY: Float = 100f,
    val overlayScale: Float = 1.0f,
    val overlayRotation: Float = 0f,
    val overlayAlpha: Float = 1.0f,
    val magicEraserBrushRadius: Float = 28f,
    val isCloudAiEraserEnabled: Boolean = true,
    val showCanvaStickersDialog: Boolean = false,
    val whiteoutBrushRadius: Float = 22f,
    val hasUnsavedChanges: Boolean = false,
    val searchQuery: String = "",
    val isSearchActive: Boolean = false,
    val searchMatchingIndices: List<Int> = emptyList(),
    val showPagesOverviewDialog: Boolean = false,
    val showExitConfirmationDialog: Boolean = false,
    val showPasswordPromptDialog: Boolean = false,
    val pendingEncryptedPdfUri: android.net.Uri? = null,
    val currentDocHistoryId: String? = null,
    val exportUri: String? = null,
    val canvasRevision: Long = 0L,
    val pdfPageCount: Int = 1,
    val currentPdfPageIndex: Int = 0,
    val activePdfUri: android.net.Uri? = null,
    val batchScannedPaths: List<String> = emptyList(),
    val currentBatchIndex: Int = 0,
    val showCloudSyncDialog: Boolean = false,
    val showCloudBackupsListDialog: Boolean = false,
    val cloudSyncResult: com.docu.editor.ui.dialogs.CloudSyncResult? = null,
    val isPerformingHandwritingOcr: Boolean = false,
    val markupColorRgb: Int = android.graphics.Color.rgb(255, 235, 59),
    val markupStrokeWidth: Float = 28f,
    val penColorRgb: Int = android.graphics.Color.rgb(220, 38, 38),
    val penStrokeWidth: Float = 6f,
    val documentTitle: String = "Untitled Document",
    val showRenameDialog: Boolean = false,
    val selectedShapeType: ShapeType = ShapeType.RECTANGLE,
    val shapeStrokeWidth: Float = 6f,
    val shapeStrokeColorRgb: Int = android.graphics.Color.rgb(220, 38, 38),
    val shapeFillColor: Int? = null,
    val redactionBrushRadius: Float = 24f,
    val canvasLayers: List<DocumentCanvasLayer> = emptyList(),
    val selectedLayerId: String? = null,
    val showEditTextLayerDialog: Boolean = false,
    val editingTextLayer: DocumentCanvasLayer? = null,
    val showBackgroundRemovalDialog: Boolean = false,
    val showCanvaMockupsDialog: Boolean = false,
    val showCanvaTextStudioDialog: Boolean = false,
    val showCanvaBrandKitDialog: Boolean = false,
    val showCanvaMagicStudioDialog: Boolean = false,
    val showCanvaAdjustDialog: Boolean = false,
    val showCanvaAnimateDialog: Boolean = false,
    val showCanvaLayersDialog: Boolean = false,
    val activeBrandPaletteId: String = "canva_signature",
    val activeAnimationType: CanvaAnimationType = CanvaAnimationType.NONE,
    val activeStyleMatchPreset: CanvaStyleMatchPreset = CanvaStyleMatchPreset.NONE,
    val showPageSizeDialog: Boolean = false,
    val showDirectCloudUploadDialog: Boolean = false
) {
    val selectedLayer: DocumentCanvasLayer?
        get() = canvasLayers.firstOrNull { it.id == selectedLayerId }
}

